# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod
mod_version=1.8.0
mod_group=com.github.j-dill.nomowanderer
mod_id=nomowanderer
mod_name=NoMoWanderer
mod_url=https://www.curseforge.com/minecraft/mc-mods/nomowanderer
mod_authors=J-Dill
mod_license=MIT
mod_description=Adds a block and an item that prevents configurable entity spawns. Default entities are the Wandering Trader and the Plague Doctor from the Rats mod.

# Minecraft
version_mc=1.20.4
version_range_mc=[1.20, 1.21)

# Forge
version_forge=49.0.38
version_range_forge=[49,)
loader_version_range=[0,)

# Dependencies
version_curios=7.3.4+1.20.4
version_range_curios=[7,)
version_jei=17.3.0.49
#version_jer=3951643

# Curse
curse_id=354428
curse_release=release
curse_versions=1.20.4
curse_versions_forge=Minecraft 1.20:1.20.4,Java 17,Forge