# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod
mod_version=1.11.0
mod_group=com.github.j-dill.nomowanderer
mod_id=nomowanderer
mod_name=NoMoWanderer
mod_url=https://www.curseforge.com/minecraft/mc-mods/nomowanderer
mod_issues=https://github.com/J-Dill/NoMoWanderer/issues
mod_authors=J-Dill
mod_license=MIT
mod_description=Adds a block and an item that prevents configurable entity spawns. Default entities are the Wandering Trader and the Plague Doctor from the Rats mod.

# Minecraft
version_mc_major=1.21
version_mc=1.21.3
version_range_mc=[1.21, 1.22)

# Forge
version_forge=53.1.1
version_range_forge=[53,)

# NeoForge
version_neoforge=21.3.85
version_neoforge_range=[1,)

# Fabric
version_fabric=0.114.1+1.21.3
version_fabric_loader=0.16.14

# Parchment
version_parchment_mc=1.21.3
version_parchment=2024.12.07

# Dependencies
version_curios=9.5.1+1.21.1
version_jei=19.21.2.313
#version_jer=3951643

# SpectreLib
version_spectrelib=0.17.2+1.21

# Curse
curse_id=354428
