# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod
mod_version=1.8.1
mod_group=com.github.j-dill.nomowanderer
mod_id=nomowanderer
mod_name=NoMoWanderer
mod_url=https://www.curseforge.com/minecraft/mc-mods/nomowanderer
mod_issues=https://github.com/J-Dill/NoMoWanderer/issues
mod_authors=J-Dill
mod_license=MIT
mod_description=Adds a block and an item that prevents configurable entity spawns. Default entities are the Wandering Trader and the Plague Doctor from the Rats mod.

# Minecraft
version_mc_major=1.20
version_mc=1.20.4
version_range_mc=[1.20, 1.21)

# Forge
version_forge=49.0.38
version_range_forge=[49,)

# NeoForge
version_neoforge=20.4.227
version_neoforge_range=[1,)

# Fabric
version_fabric=0.92.1+1.20.4
version_fabric_loader=0.15.3

# Parchment
version_parchment_mc=1.20.4
version_parchment=2024.02.25

# Dependencies
version_curios=7.3.4+1.20.4
version_range_curios=[7,)
version_jei=17.3.0.49
#version_jer=3951643

# SpectreLib
version_spectrelib=0.15.2+1.20.4
spectrelib_range=[0.15,0.16)

# Curse
curse_id=354428
