modLoader="javafml"
loaderVersion="${neoforge_version_range}"
issueTrackerURL="${mod_issues}"
license="MIT License"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="Big shoutout to computers, without you I would have no job."
authors="${mod_authors}"
description="${mod_description}"
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"
