name: Build & Release

on:
  push:
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  version-check:
    runs-on: ubuntu-latest
    outputs:
      new-tag: v${{ steps.load-props.outputs.value }}
      continue: ${{ steps.continue-build.outputs.continue }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Current Mod Version
        uses: madhead/read-java-properties@2.1.0
        id: load-props
        with:
          file: ./gradle.properties
          property: mod_version

      - name: Retrieve Latest Version
        id: get-version
        run: |
          last_tag=$(git describe --tags --abbrev=0)
          echo "latest-tag=${last_tag:1}" >> $GITHUB_OUTPUT

      # Run the rest of the workflow only if a new version has been detected.
      - name: Continue Build?
        id: continue-build
        if: steps.load-props.outputs.value != steps.get-version.outputs.latest-tag
        run: echo "continue=true" >> $GITHUB_OUTPUT

      - name: Tag Commit w/ Version
        uses: rickstaa/action-create-tag@v1.3.7
        if: steps.continue-build.outputs.continue
        with:
          tag: v${{ steps.load-props.outputs.value }}
          github_token: ${{ secrets.TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: version-check
    if: needs.version-check.outputs.continue

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Gradle
        id: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload Forge JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-forge
          path: |
            ./forge/build/libs/*.jar
            !./forge/build/libs/*-plain.jar

      - name: Upload NeoForge JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-neoforge
          path: |
            ./neoforge/build/libs/*.jar
            !./neoforge/build/libs/*-plain.jar

      - name: Upload Fabric JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-fabric
          path: |
            ./fabric/build/libs/*.jar
            !./fabric/build/libs/*-plain.jar

  release-github:
    runs-on: ubuntu-latest
    needs: [build, version-check]
    if: needs.version-check.outputs.continue

    outputs:
      changelog: ${{ steps.get-release-changelog.outputs.body }}

    steps:
      - name: Download JARs
        uses: actions/download-artifact@v4
        with:
          pattern: jar-*
          path: ./build/jars/

      - name: Create GitHub Release
        id: create-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.TOKEN }}
          automatic_release_tag: ${{ needs.version-check.outputs.new-tag }}
          prerelease: false
          files: ./build/jars/*.jar
          
      - name: Get Release Changelog
        id: get-release-changelog
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag: ${{ steps.create-release.outputs.automatic_releases_tag }}

  release-curseforge:
    runs-on: ubuntu-latest
    needs: [version-check, build, release-github]
    if: needs.version-check.outputs.continue

    steps:
      - uses: actions/checkout@v4

      - name: Load Gradle Properties
        uses: madhead/read-java-properties@2.1.0
        id: load-props
        with:
          file: ./gradle.properties
          all: true

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: jar-*
          path: ./build/jars/

      - name: Unzip Artifacts
        run: |
          tree -d ./build/jars/
          unzip ./build/jars/jar-forge -d ./build/jars/
          unzip ./build/jars/jar-neoforge -d ./build/jars/
          unzip ./build/jars/jar-fabric -d ./build/jars/
          tree -d ./build/jars/

      - name: Upload to CurseForge - Forge
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "./build/jars/${{ steps.load-props.outputs.mod_id }}-forge-${{ steps.load-props.outputs.version_mc }}-${{ steps.load-props.outputs.mod_version }}.jar"
          game_endpoint: minecraft
          release_type: release
          game_versions: "Minecraft ${{ steps.load-props.outputs.version_mc_major }}:${{ steps.load-props.outputs.version_mc }},Java 17,Forge"
          project_id: "${{ steps.load-props.outputs.curse_id }}"
          changelog: ${{ needs.release-github.outputs.changelog }}
          changelog_type: "markdown"
          token: "${{ secrets.CURSEFORGE_API_KEY }}"

      - name: Upload to CurseForge - NeoForge
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "./build/jars/${{ steps.load-props.outputs.mod_id }}-neoforge-${{ steps.load-props.outputs.version_mc }}-${{ steps.load-props.outputs.mod_version }}.jar"
          game_endpoint: minecraft
          release_type: release
          game_versions: "Minecraft ${{ steps.load-props.outputs.version_mc_major }}:${{ steps.load-props.outputs.version_mc }},Java 17,NeoForge"
          project_id: "${{ steps.load-props.outputs.curse_id }}"
          changelog: ${{ needs.release-github.outputs.changelog }}
          changelog_type: "markdown"
          token: "${{ secrets.CURSEFORGE_API_KEY }}"

      - name: Upload to CurseForge - Fabric
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "./build/jars/${{ steps.load-props.outputs.mod_id }}-fabric-${{ steps.load-props.outputs.version_mc }}-${{ steps.load-props.outputs.mod_version }}.jar"
          game_endpoint: minecraft
          release_type: release
          game_versions: "Minecraft ${{ steps.load-props.outputs.version_mc_major }}:${{ steps.load-props.outputs.version_mc }},Java 17,Fabric"
          project_id: "${{ steps.load-props.outputs.curse_id }}"
          changelog: ${{ needs.release-github.outputs.changelog }}
          changelog_type: "markdown"
          token: "${{ secrets.CURSEFORGE_API_KEY }}"
